Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/09/2023
Var
   numero: inteiro
   tabuada: inteiro


Inicio

  para numero de 2 ate 20 passo 2 faca
  escreval("Números pares entre 1 e 20:",numero)
  fimpara

Fimalgoritmo